project:
  type: website
  output-dir: docs

title: "The Pokemon World Tournament Simulation Analysis"
author: "Edgar Gonzalez Martinez"
date: "2026-03-22"

format:
  html:
    theme: cyborg
    toc: true
    code-fold: false
